### ISSUE TITLE
Chapter 4 Assets Link Not Working

### ISSUE THREAD

**Issue by JamWils** [d-ronnqvist/SCNBook-code#11]
Hi,

Great book so far.  I was going to use the models and other assets supplied in Chapter 4 pg 44, but the link takes me to apple.com.  Just thought you should know.

Thanks,
James

**Comment by d-ronnqvist** [comment]
Thanks for pointing that out.

**Comment by d-ronnqvist** [comment]
This problem has been fixed and will be available in a small update coming in a few days
