### ISSUE TITLE
The book is not available in India :(

### ISSUE THREAD

**Issue by sidshekar** [d-ronnqvist/SCNBook-code#13]
Could you make the app/book available in India as I am not able to purchase it. Any specific reason why it is not available or released in India? 

Also will there be a swift version of the book?

Thanks.

**Comment by d-ronnqvist** [comment]
It's an issue that I'm aware of. The book is currently available in the 51 countries that have paid books in iTunes and the iBooks Store. A full list of those countries can be found in [this iTunes support page][list].

See issue #1 

I have plans on switching to Swift in the future, but I don't feel that I have a style of Swift code that I'm comfortable enough with.  


[list]: http://support.apple.com/en-us/TS3599

**Comment by sidshekar** [comment]
Wow india is not in the list. that really sucks. Does apple think we are
illustrates?

I know you dont have plans but cant you make a pdf version or digital ebook
version with gif images and put it on amazon? WHy limit your chances with
ibook store? You have the content ready might as well make a pdf. BUt thats
your decision.

Regarding to swift. I have also not warmed upto it. Has bugs ans
inconsistencies. Objecttive-C is still sort of my go to language. maybe in
Xcode7 swift will be better :).

**Comment by d-ronnqvist** [comment]
I'm guessing that availability comes down to negotiations with the large publishers.

As for publishing in other formats and stores: I don't consider PDF a good enough alternative fallback and there is work in creating fallbacks for interactive elements, 3D objects, etc. It is something that I am considering at some point, but I want to avoid maintaining and updating two versions side by side.
