### ISSUE TITLE
SceneKit and 2D

### ISSUE THREAD

**Issue by pzbyszynski** [d-ronnqvist/SCNBook-code#9]
David,

I would love the chapter about mixing SceneKit with 2D. Especially about SceneKit and SpriteKit integration, about using 2D animations in 3D scene (or using 3D animations in 2D scene). About  standard 2D techniques like frame by frame animations using SceneKit. About using SceneKit in 2D games to achieve 3D like effects (for example zoom into the scene with parallax effects). About use of SceneKit as a tool in user interface development, data visualization etc.

Do you think chapter about 2.5D fits the scope of the book?

**Comment by d-ronnqvist** [comment]
It may and it may not. I haven't spent much time thinking about it and I don't have any good examples that aren't too specific.
